{{/* ────────────────────────────────────────────────────────────────────────
ServiceAccount 模板
─────────────────────────────────────────────────────────────────────── */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}
    service: {{ .Values.serviceType }}
